server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://db-write:5432/db_write
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true